/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as SocialEntrarRouteImport } from './routes/social_.entrar'
import { Route as SocialRelatoriosRouteImport } from './routes/social/relatorios'
import { Route as SocialRelacionamentoRouteImport } from './routes/social/relacionamento'
import { Route as SocialPublicoRouteImport } from './routes/social/publico'
import { Route as SocialPublicacoesRouteImport } from './routes/social/publicacoes'
import { Route as SocialPerfilRouteImport } from './routes/social/perfil'
import { Route as SocialMapaRouteImport } from './routes/social/mapa'
import { Route as SocialImpulsionamentosRouteImport } from './routes/social/impulsionamentos'
import { Route as SocialImportarRouteImport } from './routes/social/importar'
import { Route as SocialHistoricoRouteImport } from './routes/social/historico'
import { Route as SocialEquipeRouteImport } from './routes/social/equipe'
import { Route as SocialConteudoRouteImport } from './routes/social/conteudo'
import { Route as SocialContasRouteImport } from './routes/social/contas'
import { Route as SocialAtualizarRouteImport } from './routes/social/atualizar'
import { Route as SocialAgendaRouteImport } from './routes/social/agenda'
import { Route as RelatorioTokenRouteImport } from './routes/relatorio.$token'
import { Route as OauthRetornoRouteImport } from './routes/oauth.retorno'
import { Route as SocialRedeNetworkIdRouteImport } from './routes/social/rede.$networkId'
import { Route as SocialPublicacaoPostIdRouteImport } from './routes/social/publicacao.$postId'
import { Route as SocialEventoEventoIdRouteImport } from './routes/social/evento.$eventoId'
import { Route as SocialContaAccountIdRouteImport } from './routes/social/conta.$accountId'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialRoute,
} as any)
const SocialEntrarRoute = SocialEntrarRouteImport.update({
  id: '/social_/entrar',
  path: '/social/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRelatoriosRoute = SocialRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => SocialRoute,
} as any)
const SocialRelacionamentoRoute = SocialRelacionamentoRouteImport.update({
  id: '/relacionamento',
  path: '/relacionamento',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPublicoRoute = SocialPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPublicacoesRoute = SocialPublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPerfilRoute = SocialPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => SocialRoute,
} as any)
const SocialMapaRoute = SocialMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => SocialRoute,
} as any)
const SocialImpulsionamentosRoute = SocialImpulsionamentosRouteImport.update({
  id: '/impulsionamentos',
  path: '/impulsionamentos',
  getParentRoute: () => SocialRoute,
} as any)
const SocialImportarRoute = SocialImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => SocialRoute,
} as any)
const SocialHistoricoRoute = SocialHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => SocialRoute,
} as any)
const SocialEquipeRoute = SocialEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => SocialRoute,
} as any)
const SocialConteudoRoute = SocialConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => SocialRoute,
} as any)
const SocialContasRoute = SocialContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => SocialRoute,
} as any)
const SocialAtualizarRoute = SocialAtualizarRouteImport.update({
  id: '/atualizar',
  path: '/atualizar',
  getParentRoute: () => SocialRoute,
} as any)
const SocialAgendaRoute = SocialAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => SocialRoute,
} as any)
const RelatorioTokenRoute = RelatorioTokenRouteImport.update({
  id: '/relatorio/$token',
  path: '/relatorio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRetornoRoute = OauthRetornoRouteImport.update({
  id: '/oauth/retorno',
  path: '/oauth/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRedeNetworkIdRoute = SocialRedeNetworkIdRouteImport.update({
  id: '/rede/$networkId',
  path: '/rede/$networkId',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPublicacaoPostIdRoute = SocialPublicacaoPostIdRouteImport.update({
  id: '/publicacao/$postId',
  path: '/publicacao/$postId',
  getParentRoute: () => SocialRoute,
} as any)
const SocialEventoEventoIdRoute = SocialEventoEventoIdRouteImport.update({
  id: '/evento/$eventoId',
  path: '/evento/$eventoId',
  getParentRoute: () => SocialRoute,
} as any)
const SocialContaAccountIdRoute = SocialContaAccountIdRouteImport.update({
  id: '/conta/$accountId',
  path: '/conta/$accountId',
  getParentRoute: () => SocialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/social': typeof SocialRouteWithChildren
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/agenda': typeof SocialAgendaRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/conteudo': typeof SocialConteudoRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/importar': typeof SocialImportarRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/mapa': typeof SocialMapaRoute
  '/social/perfil': typeof SocialPerfilRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/publico': typeof SocialPublicoRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social/entrar': typeof SocialEntrarRoute
  '/social/': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/evento/$eventoId': typeof SocialEventoEventoIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
  '/social/rede/$networkId': typeof SocialRedeNetworkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/agenda': typeof SocialAgendaRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/conteudo': typeof SocialConteudoRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/importar': typeof SocialImportarRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/mapa': typeof SocialMapaRoute
  '/social/perfil': typeof SocialPerfilRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/publico': typeof SocialPublicoRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social/entrar': typeof SocialEntrarRoute
  '/social': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/evento/$eventoId': typeof SocialEventoEventoIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
  '/social/rede/$networkId': typeof SocialRedeNetworkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/social': typeof SocialRouteWithChildren
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/agenda': typeof SocialAgendaRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/conteudo': typeof SocialConteudoRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/importar': typeof SocialImportarRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/mapa': typeof SocialMapaRoute
  '/social/perfil': typeof SocialPerfilRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/publico': typeof SocialPublicoRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social_/entrar': typeof SocialEntrarRoute
  '/social/': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/evento/$eventoId': typeof SocialEventoEventoIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
  '/social/rede/$networkId': typeof SocialRedeNetworkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/social'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/agenda'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/conteudo'
    | '/social/equipe'
    | '/social/historico'
    | '/social/importar'
    | '/social/impulsionamentos'
    | '/social/mapa'
    | '/social/perfil'
    | '/social/publicacoes'
    | '/social/publico'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social/entrar'
    | '/social/'
    | '/social/conta/$accountId'
    | '/social/evento/$eventoId'
    | '/social/publicacao/$postId'
    | '/social/rede/$networkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/agenda'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/conteudo'
    | '/social/equipe'
    | '/social/historico'
    | '/social/importar'
    | '/social/impulsionamentos'
    | '/social/mapa'
    | '/social/perfil'
    | '/social/publicacoes'
    | '/social/publico'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social/entrar'
    | '/social'
    | '/social/conta/$accountId'
    | '/social/evento/$eventoId'
    | '/social/publicacao/$postId'
    | '/social/rede/$networkId'
  id:
    | '__root__'
    | '/'
    | '/social'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/agenda'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/conteudo'
    | '/social/equipe'
    | '/social/historico'
    | '/social/importar'
    | '/social/impulsionamentos'
    | '/social/mapa'
    | '/social/perfil'
    | '/social/publicacoes'
    | '/social/publico'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social_/entrar'
    | '/social/'
    | '/social/conta/$accountId'
    | '/social/evento/$eventoId'
    | '/social/publicacao/$postId'
    | '/social/rede/$networkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocialRoute: typeof SocialRouteWithChildren
  OauthRetornoRoute: typeof OauthRetornoRoute
  RelatorioTokenRoute: typeof RelatorioTokenRoute
  SocialEntrarRoute: typeof SocialEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social_/entrar': {
      id: '/social_/entrar'
      path: '/social/entrar'
      fullPath: '/social/entrar'
      preLoaderRoute: typeof SocialEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/relatorios': {
      id: '/social/relatorios'
      path: '/relatorios'
      fullPath: '/social/relatorios'
      preLoaderRoute: typeof SocialRelatoriosRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/relacionamento': {
      id: '/social/relacionamento'
      path: '/relacionamento'
      fullPath: '/social/relacionamento'
      preLoaderRoute: typeof SocialRelacionamentoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/publico': {
      id: '/social/publico'
      path: '/publico'
      fullPath: '/social/publico'
      preLoaderRoute: typeof SocialPublicoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/publicacoes': {
      id: '/social/publicacoes'
      path: '/publicacoes'
      fullPath: '/social/publicacoes'
      preLoaderRoute: typeof SocialPublicacoesRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/perfil': {
      id: '/social/perfil'
      path: '/perfil'
      fullPath: '/social/perfil'
      preLoaderRoute: typeof SocialPerfilRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/mapa': {
      id: '/social/mapa'
      path: '/mapa'
      fullPath: '/social/mapa'
      preLoaderRoute: typeof SocialMapaRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/impulsionamentos': {
      id: '/social/impulsionamentos'
      path: '/impulsionamentos'
      fullPath: '/social/impulsionamentos'
      preLoaderRoute: typeof SocialImpulsionamentosRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/importar': {
      id: '/social/importar'
      path: '/importar'
      fullPath: '/social/importar'
      preLoaderRoute: typeof SocialImportarRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/historico': {
      id: '/social/historico'
      path: '/historico'
      fullPath: '/social/historico'
      preLoaderRoute: typeof SocialHistoricoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/equipe': {
      id: '/social/equipe'
      path: '/equipe'
      fullPath: '/social/equipe'
      preLoaderRoute: typeof SocialEquipeRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/conteudo': {
      id: '/social/conteudo'
      path: '/conteudo'
      fullPath: '/social/conteudo'
      preLoaderRoute: typeof SocialConteudoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/contas': {
      id: '/social/contas'
      path: '/contas'
      fullPath: '/social/contas'
      preLoaderRoute: typeof SocialContasRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/atualizar': {
      id: '/social/atualizar'
      path: '/atualizar'
      fullPath: '/social/atualizar'
      preLoaderRoute: typeof SocialAtualizarRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/agenda': {
      id: '/social/agenda'
      path: '/agenda'
      fullPath: '/social/agenda'
      preLoaderRoute: typeof SocialAgendaRouteImport
      parentRoute: typeof SocialRoute
    }
    '/relatorio/$token': {
      id: '/relatorio/$token'
      path: '/relatorio/$token'
      fullPath: '/relatorio/$token'
      preLoaderRoute: typeof RelatorioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/retorno': {
      id: '/oauth/retorno'
      path: '/oauth/retorno'
      fullPath: '/oauth/retorno'
      preLoaderRoute: typeof OauthRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/rede/$networkId': {
      id: '/social/rede/$networkId'
      path: '/rede/$networkId'
      fullPath: '/social/rede/$networkId'
      preLoaderRoute: typeof SocialRedeNetworkIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/publicacao/$postId': {
      id: '/social/publicacao/$postId'
      path: '/publicacao/$postId'
      fullPath: '/social/publicacao/$postId'
      preLoaderRoute: typeof SocialPublicacaoPostIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/evento/$eventoId': {
      id: '/social/evento/$eventoId'
      path: '/evento/$eventoId'
      fullPath: '/social/evento/$eventoId'
      preLoaderRoute: typeof SocialEventoEventoIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/conta/$accountId': {
      id: '/social/conta/$accountId'
      path: '/conta/$accountId'
      fullPath: '/social/conta/$accountId'
      preLoaderRoute: typeof SocialContaAccountIdRouteImport
      parentRoute: typeof SocialRoute
    }
  }
}

interface SocialRouteChildren {
  SocialAgendaRoute: typeof SocialAgendaRoute
  SocialAtualizarRoute: typeof SocialAtualizarRoute
  SocialContasRoute: typeof SocialContasRoute
  SocialConteudoRoute: typeof SocialConteudoRoute
  SocialEquipeRoute: typeof SocialEquipeRoute
  SocialHistoricoRoute: typeof SocialHistoricoRoute
  SocialImportarRoute: typeof SocialImportarRoute
  SocialImpulsionamentosRoute: typeof SocialImpulsionamentosRoute
  SocialMapaRoute: typeof SocialMapaRoute
  SocialPerfilRoute: typeof SocialPerfilRoute
  SocialPublicacoesRoute: typeof SocialPublicacoesRoute
  SocialPublicoRoute: typeof SocialPublicoRoute
  SocialRelacionamentoRoute: typeof SocialRelacionamentoRoute
  SocialRelatoriosRoute: typeof SocialRelatoriosRoute
  SocialIndexRoute: typeof SocialIndexRoute
  SocialContaAccountIdRoute: typeof SocialContaAccountIdRoute
  SocialEventoEventoIdRoute: typeof SocialEventoEventoIdRoute
  SocialPublicacaoPostIdRoute: typeof SocialPublicacaoPostIdRoute
  SocialRedeNetworkIdRoute: typeof SocialRedeNetworkIdRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialAgendaRoute: SocialAgendaRoute,
  SocialAtualizarRoute: SocialAtualizarRoute,
  SocialContasRoute: SocialContasRoute,
  SocialConteudoRoute: SocialConteudoRoute,
  SocialEquipeRoute: SocialEquipeRoute,
  SocialHistoricoRoute: SocialHistoricoRoute,
  SocialImportarRoute: SocialImportarRoute,
  SocialImpulsionamentosRoute: SocialImpulsionamentosRoute,
  SocialMapaRoute: SocialMapaRoute,
  SocialPerfilRoute: SocialPerfilRoute,
  SocialPublicacoesRoute: SocialPublicacoesRoute,
  SocialPublicoRoute: SocialPublicoRoute,
  SocialRelacionamentoRoute: SocialRelacionamentoRoute,
  SocialRelatoriosRoute: SocialRelatoriosRoute,
  SocialIndexRoute: SocialIndexRoute,
  SocialContaAccountIdRoute: SocialContaAccountIdRoute,
  SocialEventoEventoIdRoute: SocialEventoEventoIdRoute,
  SocialPublicacaoPostIdRoute: SocialPublicacaoPostIdRoute,
  SocialRedeNetworkIdRoute: SocialRedeNetworkIdRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocialRoute: SocialRouteWithChildren,
  OauthRetornoRoute: OauthRetornoRoute,
  RelatorioTokenRoute: RelatorioTokenRoute,
  SocialEntrarRoute: SocialEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
